apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - image: ghcr.io/weplanx/console:latest
          imagePullPolicy: Always
          name: console
          ports:
            - containerPort: 9000
      nodeSelector:
        type: compute
---
apiVersion: v1
kind: Service
metadata:
  name: console-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: console
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: kainonly
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: kainonly.com
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "*.kainonly.com"
spec:
  rules:
    - host: console.kainonly.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console-svc
                port:
                  number: 80
