name: bit_test

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#      - run: npm install
#      - run: npm test
#      - name: Coveralls GitHub Action
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          path-to-lcov: ./coverage/report-lcov/lcov.info
