name: 自动部署

on:
  push:
    tags:
      - console-*

env:
  COS_VERSION: v0.11.0-beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v3

      - name: 缓存
        uses: actions/cache@v3
        id: cache
        with:
          path: '~/.cache'
          key: ${{ env.COS_VERSION }}

#      - name: 安装 coscli
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: |
#          mkdir -p ~/.cache
#          wget https://github.com/tencentyun/coscli/releases/download/${{ env.COS_VERSION }}/coscli-linux
#          mv ./coscli-linux ~/.cache/coscli
#          chmod +x ~/.cache/coscli
#          cat > ~/.cache/cos.yml << EOF
#          cos:
#            base:
#              secretid: ${{ secrets.COS_SECRETID }}
#              secretkey: ${{ secrets.COS_SECRETKEY }}
#              sessiontoken: ""
#            buckets:
#              - name: ${{ secrets.COS_BUCKET }}
#                alias: default
#                region: ap-guangzhou
#              - name: ${{ secrets.COS_BUCKET }}
#                alias: accelerate
#                region: accelerate
#          EOF

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: 安装依赖
        run: npm install

      - name: 构建应用
        run: npm run build

#      - name: 静态部署
#        run: |
#          ~/.cache/coscli rm cos://default/ -r -f -c ~/.cache/cos.yml
#          ~/.cache/coscli cp ./dist/console/ cos://accelerate/ -r -c ~/.cache/cos.yml

#      - name: 自动刷新 CDN
#        uses: TencentCloud/cli-action@v1
#        with:
#          secret_id: ${{ secrets.COS_SECRETID }}
#          secret_key: ${{ secrets.COS_SECRETKEY }}
#          region: ap-guangzhou
#          commands: |
#            cdn PurgePathCache --cli-unfold-argument --Paths https://console.kainonly.com/ --FlushType delete
#          output_format: json

      - name: 静态文件打包
        run: |
          cd ./dist
          zip -r ../${{ github.ref_name }}.zip ./console/

      - name: 版本发布
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.ref_name }}.zip
