name: Publish NPM Package

on:
  push:
    tags:
      - ng-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v3

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建 Angular 库
        run: |
          npm run build:ng

      - name: 发布至 NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd ./dist/library
          npm version ${{github.ref_name#ng-}}
          npm publish --access=public
