name: NPM 包发布

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v2

      - name: 安装 Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org

      - name: 安装依赖
        run: npm install

      - name: 构建 Angular 库
        run: |
          npm run build:ng
          npm run build:intgr

      - name: 发布至 NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd ./dist/angular
          npm version ${{github.ref_name}}
          npm publish --access=public
          cd ../integrate
          npm version ${{github.ref_name}}
          npm publish --access=public
