name: release

on:
  release:
    types: [ published ]
    tags:
      - v*
      - '!console-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org

      - name: Install Dependency
        run: npm install

      - run: npm run build:common

      - name: Publish Common
        run: |
          cd ./dist/common
          npm version ${{github.ref_name}}
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
