name: 单元测试

on:
  push:
    branches:
      - main
    paths:
      - 'projects/angular/**'

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - name: 检出
        uses: actions/checkout@v2

      - name: 安装 Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 安装依赖
        run: npm install

      - name: 启动单元测试
        run: npm test

      - name: 推送覆盖率至 COVERAGE
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/angular/report-lcov/lcov.info

      - name: 推送 Fossas
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
