name: testing

on:
  push:
    branches:
      - main
    paths:
      - 'projects/common/**'

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependency
        run: npm install

      - name: Start Common Test
        run: npm test

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/common/report-lcov/lcov.info

      - name: Push Fossas
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
